"""
reporter.py
───────────
Generates a markdown run report after each agent workflow execution.
Saves it to data/reports/ and prints a summary table to the terminal.
"""

import logging
from datetime import datetime
from pathlib import Path
from config import REPORTS_DIR

logger = logging.getLogger(__name__)


def generate_report(
    jobs_found: list[dict],
    jobs_to_apply: list[dict],
    applied_jobs: list[dict],
    keyword: str,
    location: str,
) -> Path:
    """
    Generates a markdown report of the run and saves it to data/reports/.

    Args:
        jobs_found:    All jobs fetched from scrapers
        jobs_to_apply: Jobs the LLM marked as APPLY (with link + score)
        applied_jobs:  Jobs actually submitted via Playwright (with status)
        keyword:       Job search keyword
        location:      Job search location

    Returns:
        Path to the saved report file.
    """
    timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
    report_path = REPORTS_DIR / f"run_{timestamp}.md"

    # ── Build source breakdown
    by_source: dict[str, int] = {}
    for job in jobs_found:
        src = job.get("source", "Unknown")
        by_source[src] = by_source.get(src, 0) + 1

    source_table_rows = "\n".join(
        f"| {src} | {count} |" for src, count in by_source.items()
    )

    # ── Build apply table
    apply_rows = ""
    for job in jobs_to_apply:
        title = job.get("title", "N/A")
        company = job.get("company", "N/A")
        link = job.get("link", "#")
        score = job.get("semantic_score", "—")
        score_str = f"{score:.2f}" if isinstance(score, float) else str(score)
        apply_rows += f"| {title} | {company} | [{link}]({link}) | {score_str} |\n"

    if not apply_rows:
        apply_rows = "| — | No jobs marked APPLY | — | — |\n"

    # ── Build applied table
    applied_rows = ""
    for job in applied_jobs:
        title = job.get("title", "N/A")
        company = job.get("company", "N/A")
        link = job.get("link", "#")
        status = job.get("status", "UNKNOWN")
        applied_rows += f"| {title} | {company} | [{link}]({link}) | {status} |\n"

    if not applied_rows:
        applied_rows = "| — | No applications submitted | — | — |\n"

    report = f"""# 🤖 Job AI Agent — Run Report
**Date:** {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
**Search:** `{keyword}` in `{location}`

---

## 📊 Summary

| Metric | Count |
|--------|-------|
| Total jobs found | {len(jobs_found)} |
| Jobs marked APPLY | {len(jobs_to_apply)} |
| Applications submitted | {len(applied_jobs)} |
| Applications succeeded | {sum(1 for j in applied_jobs if j.get("status") == "SUCCESS")} |

## 🌐 Sources

| Source | Jobs |
|--------|------|
{source_table_rows}

---

## ✅ Jobs Marked for Application

| Title | Company | Link | Semantic Score |
|-------|---------|------|---------------|
{apply_rows}
---

## 📨 Applications Submitted

| Title | Company | Link | Status |
|-------|---------|------|--------|
{applied_rows}
---
*Report generated by Job AI Agent*
"""

    report_path.write_text(report, encoding="utf-8")
    logger.info(f"Run report saved to: {report_path}")

    # ── Print terminal summary
    _print_terminal_summary(len(jobs_found), len(jobs_to_apply), len(applied_jobs), keyword, location, by_source)

    return report_path


def _print_terminal_summary(
    found: int,
    to_apply: int,
    applied: int,
    keyword: str,
    location: str,
    by_source: dict,
):
    bar = "─" * 52
    print(f"\n╭{bar}╮")
    print(f"│  🤖  Job AI Agent — Run Summary{' ' * 19}│")
    print(f"├{bar}┤")
    print(f"│  Search   : {keyword} in {location:<34}│"[:56] + "│")
    print(f"├{bar}┤")
    print(f"│  {'Metric':<28} {'Count':>6}{'':>14}│")
    print(f"│  {'─'*28} {'─'*6}{'':>14}│")
    print(f"│  {'Jobs Found':<28} {found:>6}{'':>14}│")
    print(f"│  {'Jobs Marked APPLY':<28} {to_apply:>6}{'':>14}│")
    print(f"│  {'Applications Submitted':<28} {applied:>6}{'':>14}│")
    print(f"├{bar}┤")
    print(f"│  {'Source':<28} {'Jobs':>6}{'':>14}│")
    print(f"│  {'─'*28} {'─'*6}{'':>14}│")
    for src, count in by_source.items():
        print(f"│  {src:<28} {count:>6}{'':>14}│")
    print(f"╰{bar}╯\n")
